include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/**.g.dart]
  language:
    strict-raw-types: true

linter:
  rules:
    # Error rules:
    always_use_package_imports: true
    avoid_returning_null_for_future: true
    discarded_futures: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true

    # Style Rules:
    always_declare_return_types: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    constant_identifier_names: false
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_string_in_part_of_directives: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options