name: select2dot1
description: Select2dot1 give you a customizable single/multiple select box with support for 
  searching, group option, extra info and avatar. Select2dot1 works using overlay
  (web, desktop) and modal (mobile) and is fully customizable by settings and builder.
version: 0.0.1
homepage: https://select2dot1.site
repository: https://github.com/romanjrdykyj/select2dot1
issue_tracker: https://github.com/romanjrdykyj/select2dot1/issues
screenshots:
  - description: 'This screenshot shows Select2dot1 in mobile version'
    path: screenshots/mobile_example.webp
  - description: 'This screenshot shows Select2dot1 in desktop version'
    path: screenshots/desktop_example.webp


environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  dart_code_metrics: ">=4.20.0 <6.0.0"
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  pubspec_dependency_sorter: ^0.0.2

flutter:
